[package]
name = "lightctl"
version = "0.1.1"
edition = "2021"
authors = ["blurrycat"]
license = "MIT"
repository = "https://github.com/blurrycat/lightctl"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
colored = "2"
rustbus = "0.19"
